# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
  lane :metrics do
    scan(
      scheme: "platonWallet", 
      code_coverage: true, 
      derived_data_path: "./DerivedData", 
      output_directory: "./reports", 
      device: "iPhone X",
      reinstall_app: true,
      app_identifier: "com.platon.aton"
      )
    # slather(
    #   cobertura_xml: true, 
    #   scheme: "platonWalletTests", 
    #   build_directory: "./DerivedData", 
    #   output_directory: "./reports", 
    #   proj: "./platonWallet.xcodeproj", 
    #   workspace: "./platonWallet.xcworkspace", 
    #   ignore: ["*ViewController*.swift", "*view*.swift", "*View*.swift", "*UI*.swift"],
    #   binary_basename: "platonWallet")
    # lizard(source_folder: "./platonWallet", language: "swift", export_type: "xml", report_file: "reports/lizard-report.xml")
    # swiftlint(config_file: "./fastlane/.swiftlint.yml", output_file: "./reports/swiftlint.txt", ignore_exit_status: true)
    # sonar
  end
  lane :tests do
  	run_tests(
  		workspace: "platonWallet.xcworkspace", 
  		devices: ["iPhone 8 Plus"],
  		scheme: "platonWalletTests", 
  		code_coverage: true)
  end
  lane :xcov do
  	xcov(
  		workspace: "platonWallet.xcworkspace",
  		scheme: "platonWalletTests",
  		output_directory: "xcov_output")
  end
end
