# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

def target_pods
    pod 'Spring', :git => 'https://github.com/MengTo/Spring.git'
    pod 'RealmSwift', '~> 4.3.0'
    pod 'BigInt', '4.0', inhibit_warnings: true
    pod 'CryptoSwift', '~> 0.10.0'
    pod 'TrezorCrypto', '0.0.9', inhibit_warnings: true
    pod 'SwiftLint', '0.30.1', :configurations => ['Debug']
    pod 'RTRootNavigationController', '0.7.1'
    pod 'SnapKit', '~> 4.0.0'

    pod 'Localize-Swift', '~> 2.0'
    pod 'UITextView+Placeholder'
    pod 'MBProgressHUD', '~> 1.2.0'
    pod 'ScryptSwift', '0.0.1'
    pod 'SwipeCellKit', '2.5.4'
    pod 'EmptyDataSet-Swift', '~> 4.2.0'
    pod 'SwiftReorder', '~> 6.0'

    # Web3 dependencies BigInt CryptoSwift secp256k1.swift
    #pod 'BigInt', '~> 3.1'
    #pod 'CryptoSwift', '~> 0.8'
    pod 'secp256k1.swift', '~> 0.1'
    pod 'Alamofire', '4.8.1'

    # Pods for platonWallet

#    pod 'platonWeb3', :path => '../../SDK/client-sdk-ios/'
    pod 'platonWeb3', '~> 0.13.0'
    pod 'MJRefresh'
    pod 'Kingfisher'

    pod 'UMCCommon'
    pod 'UMCAnalytics'
    pod 'UMCCommonLog'
    pod 'UMCSecurityPlugins'
    pod 'UMCShare/Social/ReducedSina'
    pod 'UMCShare/Social/Facebook'
    pod 'UMCShare/Social/Twitter'

    pod 'SwiftMonkeyPaws'
    pod 'OHHTTPStubs/Swift', :configurations => ['Debug']
    pod 'GzipSwift'
    pod 'ZXingObjC'
    # Reveal
    pod 'Reveal-SDK', '~> 24.0' , :configurations => ['Debug']
end

target 'platonWalletUAT' do
    use_frameworks!
    target_pods


#    target 'platonWalletTests' do
#        inherit! :search_paths
#        # Pods for testing
#    end
#
#    target 'platonWalletUITests' do
#        inherit! :search_paths
#        # Pods for testing
#        pod 'SwiftMonkey'
#    end
end

target 'platonWalletParallelNet' do
  use_frameworks!
  target_pods

end



target 'platonWallet' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  target_pods


  target 'platonWalletTests' do
      inherit! :search_paths
      # Pods for testing
  end
  
  target 'platonWalletUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'SwiftMonkey'
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if ['ScryptSwift'].include? target.name
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Owholemodule'
            end
        end
    end
end
